<?php
// sets up autoloading, autoload.php is a file automatically
// generated by composer, it defines a hash table that uses
// class name as key and file path as value.
// And registers autoloading with spl_autoload_register (http://php.net/manual/en/function.spl-autoload-register.php )
//
// @see http://getcomposer.org/doc/01-basic-usage.md for detail usage

// Raise error reporting level
// and displays all errors
error_reporting( E_ALL | E_STRICT );
ini_set('display_errors','On');
ini_set('display_startup_errors','On');

require_once 'Vendors/autoload.php';

?>